<?php

namespace MemberBundle\Repository;

/**
 * DailyServiceOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyServiceOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
