<?php

namespace MemberBundle\Repository;

/**
 * MoralMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoralMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
