security:
    access_control:
        -
            path: ^/internalaccount/list
            roles:
                - ROLE_ADMINISTRATOR
                - ROLE_MANAGER
                - ROLE_BOARD
        -
            path: ^/internalaccount/new
            roles:
                - ROLE_ADMINISTRATOR
                - ROLE_MANAGER
                - ROLE_BOARD
        -
            path: ^/classe/list
            roles:
                - ROLE_ADMINISTRATOR
                - ROLE_MANAGER
                - ROLE_BOARD
        -
            path: ^/classe/new
            roles:
                - ROLE_ADMINISTRATOR
                - ROLE_MANAGER
                - ROLE_BOARD
        -
            path: ^/loanparameter/new
            roles:
                - ROLE_ADMINISTRATOR
                - ROLE_MANAGER
                - ROLE_BOARD
        -
            path: ^/loanparameter/list
            roles:
                - ROLE_ADMINISTRATOR
                - ROLE_MANAGER
                - ROLE_BOARD
        -
            path: ^/eleve/[0-9]+/show
            roles:
                - ROLE_USER
        -
            path: ^/login$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/self/register$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/resetting$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
