<?php

namespace ReportBundle\Repository;

/**
 * GeneralLedgerBalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralLedgerBalanceRepository extends \Doctrine\ORM\EntityRepository
{
}
