<?php

namespace AccountBundle\Repository;

/**
 * DailySavingAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailySavingAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
