<?php

namespace AccountBundle\Repository;

use AccountBundle\Entity\Loan;
use AccountBundle\Entity\Operation;
use ClassBundle\Entity\InternalAccount;
use Doctrine\ORM\EntityRepository;
use MemberBundle\Entity\Member;
use ReportBundle\Entity\GeneralLedgerBalance;
use UserBundle\Entity\Utilisateur;

/**
 * LoanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanRepository extends EntityRepository
{
    /**
     * @param Utilisateur $currentUser
     * @param Loan $loan
     * @param Member $member
     * @param InternalAccount $internalAccount
     */
    public function saveLoanOperation(Utilisateur $currentUser, Loan $loan, Member $member, InternalAccount $internalAccount)
    {
        $operation = new Operation();
        $operation->setTypeOperation(Operation::TYPE_CASH_OUT);
        $operation->setCurrentUser($currentUser);
        $operation->setDateOperation($loan->getDateLoan());
        $operation->setAmount($loan->getLoanAmount());
        $operation->setMember($member);
        $operation->setBalance($internalAccount->getBalance());
        $operation->setRepresentative($member->getName());
        $this->getEntityManager()->persist($operation);
    }

    /**
     * @param Loan $loan
     * @param Utilisateur $currentUser
     * @param InternalAccount $internalAccount
     * @param Member $member
     */
    public function saveLoanInGeneralLedger(Loan $loan, Utilisateur $currentUser, InternalAccount $internalAccount, Member $member)
    {
        $ledgerBalanceLoan = new GeneralLedgerBalance();
        $ledgerBalanceLoan->setTypeOperation(Operation::TYPE_CASH_OUT);
        $ledgerBalanceLoan->setCredit($loan->getLoanAmount());
        $ledgerBalanceLoan->setCurrentUser($currentUser);
        $ledgerBalanceLoan->setDateOperation($loan->getDateLoan());
        $em = $this->getEntityManager();
        $latestEntryGBL = $em->getRepository(GeneralLedgerBalance::class)->findOneBy([],['id' => 'DESC']);
        if ($latestEntryGBL) {
            $ledgerBalanceLoan->setBalance($latestEntryGBL->getBalance() - $loan->getLoanAmount());
        }else{
            $ledgerBalanceLoan->setBalance($loan->getLoanAmount());
        }
        $ledgerBalanceLoan->setAccount($internalAccount);
        $ledgerBalanceLoan->setRepresentative($member->getName());
        $ledgerBalanceLoan->setAccountBalance($internalAccount->getBalance());
        $ledgerBalanceLoan->setAccountTitle($internalAccount->getAccountName()." A/C_".$member->getMemberNumber());
        $ledgerBalanceLoan->setMember($loan->getPhysicalMember());
        $em->persist($ledgerBalanceLoan);
    }

    /**
     * @param Utilisateur $currentUser
     * @param Loan $loan
     * @param Member $member
     * @param InternalAccount $accountProcessing
     */
    public function saveLoanProcessingFeesOperation(Utilisateur $currentUser, Loan $loan, Member $member, InternalAccount $accountProcessing)
    {
        $operationProcessing = new Operation();
        $operationProcessing->setTypeOperation(Operation::TYPE_CASH_IN);
        $operationProcessing->setCurrentUser($currentUser);
        $operationProcessing->setDateOperation($loan->getDateLoan());
        $operationProcessing->setAmount($loan->getLoanProcessingFees());
        $operationProcessing->setMember($loan->getPhysicalMember());
        $operationProcessing->setRepresentative($member->getName());
        $operationProcessing->setBalance($accountProcessing->getBalance());

        $this->getEntityManager()->persist($operationProcessing);
    }

    /**
     * @param Loan $loan
     * @param Utilisateur $currentUser
     * @param InternalAccount $accountProcessing
     * @param Member $member
     */
    public function saveProcessingFeesInGeneralLedger(Loan $loan, Utilisateur $currentUser, InternalAccount $accountProcessing, Member $member)
    {
        $em = $this->getEntityManager();
        $ledgerBalanceProcessingFees = new GeneralLedgerBalance();
        $ledgerBalanceProcessingFees->setTypeOperation(Operation::TYPE_CASH_IN);
        $ledgerBalanceProcessingFees->setDebit($loan->getLoanProcessingFees());
        $ledgerBalanceProcessingFees->setCurrentUser($currentUser);
        $ledgerBalanceProcessingFees->setDateOperation($loan->getDateLoan());
        $latestEntryGBL = $em->getRepository(GeneralLedgerBalance::class)->findOneBy([],['id' => 'DESC']);
        if ($latestEntryGBL) {
            $ledgerBalanceProcessingFees->setBalance($latestEntryGBL->getBalance() + $loan->getLoanProcessingFees());
        }else{
            $ledgerBalanceProcessingFees->setBalance($loan->getLoanProcessingFees());
        }
        $ledgerBalanceProcessingFees->setAccount($accountProcessing);
        $ledgerBalanceProcessingFees->setRepresentative($member->getName());
        $ledgerBalanceProcessingFees->setAccountBalance($accountProcessing->getBalance());
        $ledgerBalanceProcessingFees->setAccountTitle($accountProcessing->getAccountName()." A/C_".$member->getMemberNumber());
        $ledgerBalanceProcessingFees->setMember($loan->getPhysicalMember());
        $em->persist($ledgerBalanceProcessingFees);
    }
}
