<?php

namespace AccountBundle\Repository;

/**
 * LoanHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
