<?php

namespace AccountBundle\Repository;

/**
 * ReportItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportItemRepository extends \Doctrine\ORM\EntityRepository
{
}
