<?php

namespace AccountBundle\Repository;

/**
 * SavingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavingRepository extends \Doctrine\ORM\EntityRepository
{
}
