<?php

namespace ClassBundle\Repository;

/**
 * InternalAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternalAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
