<?php

namespace ConfigBundle\Repository;

/**
 * TransactionIncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionIncomeRepository extends \Doctrine\ORM\EntityRepository
{
}
